export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const LOGIN_IN = "LOGIN_IN";
export const LOGIN_OUT = "LOGIN_OUT";

export const INIT_HOME_DATA = "INIT_HOME_DATA";
export const SAVE_FINISH = "SAVE_FINISH";
export const ADD_ROWDATA = "ADD_ROWDATA";
export const DELETE_ROWDATA = "DELETE_ROWDATA";
export const CHANGE_VALUE = "CHANGE_VALUE";
export const CLOSE_FINISHTIP = "CLOSE_FINISHTIP";

export const CREATE_CHANGE_VALUE="CREATE_CHANGE_VALUE";
export const CREATE_SAVE="CREATE_SAVE";